<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account has already been disabled' => 'Tài khoản đã bị vô hiệu hóa',
    'Account successfully disconnected' => 'Bạn đã ngắt kết nối thành công khỏi tài khoản của mình',
    'Account updated' => 'gia hạn tài khoản',
    'Bind account' => 'Tài khoản ràng buộc',
    'Can not disconnect single authentication method. Please fill email and password and try again' => 'Một kết nối xác thực duy nhất không thể bị ngắt kết nối. Vui lòng nhập email và mật khẩu của bạn và thử lại',
    'Cancel' => 'Hủy bỏ',
    'Changing your email requires email confirmation' => 'Xác nhận email đã thay đổi là bắt buộc',
    'Connected' => 'kết nối',
    'Create Time' => 'thời gian tạo',
    'Disconnect' => 'ngắt kết nối',
    'Full Name' => 'Tên đầy đủ',
    'Go home' => 'đi đến trang chủ',
    'Go to my account' => 'vào tài khoản của tôi',
    'Guests can not disconnect accounts' => 'Khách không thể hủy liên kết tài khoản',
    'ID' => 'ID',
    'Instructions to reset your password have been sent' => 'Lệnh đặt lại mật khẩu đã được gửi',
    'Invalid key' => 'Khóa sai',
    'Keychain' => 'Móc khóa',
    'Language' => 'Ngôn ngữ',
    'Linking social network accounts (can be several) to your account will allow you to enter in a single click.' => 'Liên kết tài khoản hiện tại với tài khoản mạng xã hội của bạn',
    'Log in here' => 'đăng nhập tại đây',
    'Login' => 'đăng nhập',
    'Password has been reset' => 'mật khẩu đã được đặt lại',
    'Passwords do not match' => 'Mật khẩu không hợp lệ',
    'Pending email confirmation: [ {newEmail} ]' => 'Email không được chấp thuận: [{newEmail}]',
    'Profile' => 'Hồ sơ',
    'Resend' => 'gửi lại',
    'Reset' => 'cài lại',
    'Start Page' => 'trang bắt đầu',
    'Submit' => 'Gửi đi',
    'This account has already been connected' => 'Tài khoản này đã bị ngắt kết nối',
    'Update' => 'Cập nhất',
    'Update Time' => 'Cập nhật thời gian',
    'User ID' => 'TênID',
    'Yii 2 User' => '',
    'Your email [ {email} ] has been confirmed' => 'Email [{email}] đã được xác nhận',
    'or' => 'Hoặc',
    '{attribute} can contain only letters, numbers, and "_"' => 'Các giá trị thuộc tính {thuộc tính} chỉ có thể chứa các chữ cái, số và "_"',
    'Сan not disconnect a foreign account' => 'Không thể hủy liên kết các tài khoản bên ngoài',
];

